api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:   rest
    resource:   Jarvis\ApiBundle\Controller\UserController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc