# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

        db_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/api
            http_basic: ~
            provider: db_provider

            anonymous: ~
            logout: ~

            guard:
                authenticators:
                    - app.token_authenticator

    access_control:
        - { path: ^/, roles: ROLE_USER }