AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        userId:
            type: integer
            column: user_id
        categoryId:
            type: integer
            column: category_id
        deadline:
            type: datetime
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
